### ISSUE TITLE
Zed language keywords/identifiers are case sensitive

### ISSUE THREAD

**Issue by SoftTools59654** [brimdata/super#5049]
When one of the command characters is written with a capital letter, an error will be given and the command will not be executed

Of course, it is not a major problem

![image](https://github.com/brimdata/zui/assets/150426297/8df2faa5-fb8b-4a60-9b92-af28278482e9)

**Comment by philrz** [comment]
@SoftTools59654: I've moved your issue to the Zed repository and re-framed it in what I think is a more accurate way. Right now the Zed language keywords like `count` are case sensitive and this is by design. There are certainly other languages with case insensitive keywords such that variations like `COUNT` or even mixed case like `couNt` could be considered valid. It sounds like you're effectively casing a vote for case-insensitive treatment. It's not something that's been widely discussed within the core Dev team nor have other community members asked about varying the behavior here. However, we can certainly discuss the topic and hold this issue open so others may find it and express their preferences. You'll see updates here if changes are planned.

**Comment by philrz** [comment]
Verified in super commit 2965a1d.

Per linked PR #5404, as part of the work on evolving the language into SuperSQL, function names are now case insensitive in the parser. For instance, the following now works where it failed for the community user in the past.

```
$ super -version
Version: v1.18.0-87-g2965a1d0

$ echo '{"foo": "bar"}' | super -c 'couNt()' -
1(uint64)
```

At the moment there's not yet a Zui release that uses the new SuperSQL language, but when the app comes back in some form (currently planned to be called "SuperDB Desktop") this will work there as well.

Thanks @mccanne!
